#!/usr/bin/env python
"""Generate index.html for GitHub Pages from exported notebook HTML files."""

import os

HTML_DIR = "results/html"

SECTIONS = {
    "Simulation Validation": {
        "description": (
            "Synthetic DMS data generation, model fitting, and validation "
            "against known ground truth."
        ),
        "pages": [
            ("simulation/sim_01_data_simulation.html", "Data Simulation"),
            ("simulation/sim_02_model_fitting.html", "Model Fitting"),
            ("simulation/sim_03_evaluation.html", "Evaluation"),
            ("simulation/sim_04_visualization.html", "Visualization"),
        ],
    },
    "Spike Analysis": {
        "description": (
            "Empirical analysis of SARS-CoV-2 spike homologs (Delta, BA.1, BA.2) "
            "using joint deep mutational scanning models."
        ),
        "pages": [
            ("spike/spike_01_data_loading.html", "Data Loading"),
            ("spike/spike_02_exploratory_stats.html", "Exploratory Statistics"),
            ("spike/spike_03_fit_models.html", "Model Fitting"),
            ("spike/spike_04_model_evaluation.html", "Model Evaluation"),
            ("spike/spike_05_cross_validation.html", "Cross Validation"),
            ("spike/spike_06_global_epistasis.html", "Global Epistasis"),
            ("spike/spike_07_shifted_mutations.html", "Shifted Mutations"),
            ("spike/spike_08_naive_comparison.html", "Naive Comparison"),
            ("spike/spike_09_linear_comparison.html", "Linear Comparison"),
            ("spike/spike_10_validation.html", "Experimental Validation"),
            (
                "spike/spike_11_reference_sensitivity.html",
                "Reference Sensitivity",
            ),
            (
                "spike/spike_12_sparsity_correlation.html",
                "Sparsity & Correlation",
            ),
        ],
    },
    "Supplemental": {
        "description": "Publication figures and structural analysis.",
        "pages": [
            (
                "supplemental/supplemental_sim_figures.html",
                "Simulation Manuscript Figures",
            ),
            (
                "supplemental/supplemental_structure.html",
                "Spike Structure Analysis",
            ),
        ],
    },
}


def generate_html():
    sections_html = ""
    for title, info in SECTIONS.items():
        existing_pages = [
            (path, label)
            for path, label in info["pages"]
            if os.path.exists(os.path.join(HTML_DIR, path))
        ]
        if not existing_pages:
            continue
        links = "\n".join(
            f'            <li><a href="{path}">{label}</a></li>'
            for path, label in existing_pages
        )
        sections_html += f"""
        <section>
            <h2>{title}</h2>
            <p>{info["description"]}</p>
            <ul>
{links}
            </ul>
        </section>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SARS-CoV-2 Spike multidms Analysis</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 0 20px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{ color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }}
        h2 {{ color: #16213e; margin-top: 30px; }}
        a {{ color: #0066cc; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        ul {{ list-style-type: none; padding-left: 0; }}
        li {{ padding: 4px 0; }}
        li::before {{ content: "\\25B6  "; color: #0066cc; font-size: 0.7em; }}
        section {{ margin-bottom: 30px; }}
        p {{ color: #555; }}
        footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0;
                 font-size: 0.9em; color: #888; }}
    </style>
</head>
<body>
    <h1>SARS-CoV-2 Spike multidms Analysis</h1>
    <p>
        Analysis from <em>Jointly modeling deep mutational scans identifies shifted
        mutational effects among SARS-CoV-2 spike homologs</em>.
        Source code:
        <a href="https://github.com/matsengrp/SARS-CoV-2_spike_multidms">GitHub</a>.
    </p>
{sections_html}
    <footer>
        Generated by the Snakemake pipeline. Each page is an executed
        Jupyter notebook converted to HTML.
    </footer>
</body>
</html>
"""


if __name__ == "__main__":
    html = generate_html()
    os.makedirs(HTML_DIR, exist_ok=True)
    with open(f"{HTML_DIR}/index.html", "w") as f:
        f.write(html)
    print(f"Generated {HTML_DIR}/index.html")
